/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jni_JniInterface */

#ifndef _Included_jni_JniInterface
#define _Included_jni_JniInterface
#ifdef __cplusplus
extern "C" {
#endif
	/*
	 * Class:     jni_JniInterface
	 * Method:    getch
	 * Signature: ()C
	 */
	JNIEXPORT jchar JNICALL Java_jni_JniInterface_getch
	(JNIEnv*, jclass);

	/*
	 * Class:     jni_JniInterface
	 * Method:    getstr
	 * Signature: ()Ljava/lang/String;
	 */
	JNIEXPORT jstring JNICALL Java_jni_JniInterface_getstr
	(JNIEnv*, jclass);

#ifdef __cplusplus
}
#endif
#endif
